### PR TITLE
Package as module, clean up

### PR DESCRIPTION
**Pull request by dunnkers**
Hi!

I wrapped the code in a module, so I could more easily install FeatBoost in fseval. It's now installable using:

```shell
pip install git+https://github.com/amjams/FeatBoost.git
```

```python
from featboost import FeatBoostClassifier

clf = FeatBoostClassifier()
clf.fit(X, y)
```

Also: can I get access to the feature ranking vector, `feature_importances_`? It's not set during the algorithm, but it'd be useful to me to get the raw ranking. A tested using [a Notebook](https://colab.research.google.com/drive/10MpKQde14SHZKwZ3O7YEDbf5LR1X162X#scrollTo=6k1_VY70FYGI) to see whether it does.

Cheers,
Jeroen

### CODE REVIEW

**Comment by amjams** [comment]
That's cool, Jeroen! 

What do you mean by access to that vector? You could of course set it as an attribute so that you can retrieve it at the end of a run of the algorithm. Is that what you mean?

**Comment by dunnkers** [comment]
> That's cool, Jeroen!
> 
> What do you mean by access to that vector? You could of course set it as an attribute so that you can retrieve it at the end of a run of the algorithm. Is that what you mean?

Well, even though FeatBoost returns a feature subset, I'd also like to have a feature ranking with scores, if there is any. I put a little example in [this](https://colab.research.google.com/drive/10MpKQde14SHZKwZ3O7YEDbf5LR1X162X#scrollTo=ulncgKCMOP1P) Notebook.

**Comment by dunnkers** [comment]
By the way - my current line-up of feature rankers/selectors can be found here:

https://github.com/dunnkers/fseval/tree/master/fseval/conf/estimator

I'm in the process of adding more, hopefully many more.

**Comment by amjams** [comment]
> Well, even though FeatBoost returns a feature subset, I'd also like to have a feature ranking with scores, if there is any. I put a little example in [this](https://colab.research.google.com/drive/10MpKQde14SHZKwZ3O7YEDbf5LR1X162X#scrollTo=ulncgKCMOP1P) Notebook.

I see what you're trying to do. The thing is, the feature ranking changes at every iteration (based on the boosting). So in my opinion, your best bet is an aggregate of the feature_importance vector over how many iterations the algorithm took (like average then normalise). Otherwise, the first instance of fetaure_importance is just the one from XGBoost which is used in the first iteration.

**Comment by amjams** [comment]
> > Well, even though FeatBoost returns a feature subset, I'd also like to have a feature ranking with scores, if there is any. I put a little example in [this](https://colab.research.google.com/drive/10MpKQde14SHZKwZ3O7YEDbf5LR1X162X#scrollTo=ulncgKCMOP1P) Notebook.
> 
> I see what you're trying to do. The thing is, the feature ranking changes at every iteration (based on the boosting). So in my opinion, your best bet is an aggregate of the feature_importance vector over how many iterations the algorithm took (like average then normalise). Otherwise, the first instance of fetaure_importance is just the one from XGBoost which is used in the first iteration.

If you're having trouble with the above, you could just assign an integer rank to the selected features (ordered) and set the non-selected to zero (if your goal is just to quickly make featboost compatible with your pipeline. And then later, we could set up a meeting and have a look together on how to get a more meaningful importance score. I just looked at the code and it's a little messy, but basically you can get those feature importances from the input ranking function.

**Comment by dunnkers** [comment]
I understand. Currently, my pipeline uses the `feature_importances` attribute to do two things:

1. To run a validation estimator on feature subsets, starting with including only the highest ranked feature and then going downward.
2. To score the quality of the feature ranking using the 'ground-truth' relevant dataset features. Which, like we discussed in the meetings, is currently computed with an R2- and Log Loss score.

For FeatBoost, (1) can be easily achieved by using the feature ranking output. For (2), however, we would need a conversion. Like illustrated above; I could just normalize the ranking to let it be in the range [0, 1]. I would only compare these scores to other subset selectors, however, because the algorithms outputting feature importance scores directly might get an unfair advantage.

For (2) I think I will go with the approach I just described above; score feature subset selectors with the R2 and Log-Loss metric but don't compare them to algorithms that compute feature importance scores directly.

But; if you think FeatBoost can output a meaningful feature importance score, like the aggregation you describe above, we can look into implementing it.

P.S. did you see my mail? - with the link to the results dashboard.

**Comment by amjams** [comment]
> But; if you think FeatBoost can output a meaningful feature importance score, like the aggregation you describe above, we can look into implementing it.

I think I can find a more meaningful output. I'm actually interested how it would perform, so I'll look into it. Speaking of which, I was looking at feature score (importance) aggregation and found this paper on rank aggregation (https://ieeexplore.ieee.org/abstract/document/6252467). You've probably come across it I guess. I find the stuff at the beginning of section IV very interesting, "Condorcet" specially.

**Comment by amjams** [comment]
I added an attribute "feature_importances_array_". It stores every time feat boost computes feature importances. There might be some confusions with it now, because of how the algorithm resets (and that affects the iteration number). So for now, the array appends each time feature importances are computed.. and then we can process them further. I added to the collab some cells on how we could deal with those.. basically normalize by colums (features) then normalize by row. It doesn't run now, because the collab is using your own version of featboost, but I hope it's clear. Let me know if it's not.

**Comment by dunnkers** [comment]
Nice! I currently added FeatBoost using your method, like so:

https://github.com/dunnkers/fseval/blob/master/fseval/estimators/featboost.py

So I think I can start running FeatBoost in the benchmark 🙌🏻

>Speaking of which, I was looking at feature score (importance) aggregation and found this paper on rank aggregation (https://ieeexplore.ieee.org/abstract/document/6252467). You've probably come across it I guess. I find the stuff at the beginning of section IV very interesting, "Condorcet" specially.

Hadn't seen this yet! Interesting.

**Pull request merged**
